export enum Status {
    NONE = "NONE",
    DRAFT = "DRAFT",
    SUBMITTED = "SUBMITTED",
    DECLINED = "DECLINED",
    APPROVED = "APPROVED",
    DONE = "DONE",
    VERIFYING = "VERIFYING",
    DOCUMENT_DECLINED = "DOCUMENT_DECLINED",
    VERIFIED = "VERIFIED",
    CLOSED = "CLOSED",
    DISCARDED = "DISCARDED",
}
